# Generated by Django 2.2.5 on 2019-11-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammardetector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grammar',
        ),
    ]
