# Generated by Django 2.2.5 on 2020-04-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammardetector', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrees',
            fields=[
                ('id_entree', models.AutoField(primary_key=True, serialize=False)),
                ('entree', models.TextField()),
            ],
            options={
                'db_table': 'Entrees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prononciations',
            fields=[
                ('id_prononciation', models.AutoField(primary_key=True, serialize=False)),
                ('prononciation', models.TextField()),
            ],
            options={
                'db_table': 'Prononciations',
                'managed': False,
            },
        ),
    ]
